name: Trigger auto deployment for pcav-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pcav-app-AutoDeployTrigger-be41a6aa-1b02-4412-89cc-41d3c29728ab.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PCAVAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PCAVAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PCAVAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.PCAVAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PCAVAPP_REGISTRY_PASSWORD }}
          containerAppName: pcav-app
          resourceGroup: ProdControlAV-Group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

      - name: Apply secret & env vars
        run: |
          az containerapp secret set \
            -n prodcontrolav-api \
            -g prodcontrolav-rg \
            --secrets db-connstr='${{ secrets.SQL_CONNECTION_STRING }}'
      
          az containerapp update \
            -n prodcontrolav-api \
            -g prodcontrolav-rg \
            --set-env-vars ConnectionStrings__DefaultConnection=secretref:db-connstr ASPNETCORE_URLS=http://+:8080




